### ISSUE TITLE
Stats on users start/leave meeting

### ISSUE THREAD

**Issue by ghost** [Perilous-Programmer/BigBlueButton-Tools#1]
Hi Perilous,
first of all congratulations for the tool!
We are using Big Blue Button for the covid emergency and we are trying to understand how to see when the participant enters the meeting and when he leaves, are you going to implement it or can you give us advice?

Thanks again!

**Comment by Perilous-Programmer** [comment]
Thank you. 
The data shown in the page is updated after every 20 seconds
I have many more features to implement in this page. like highlighting the new users and meeting when the data refreshes and link to join the meeting for monitoring etc

**Comment by helios-ventures** [comment]
Hi Perilous,

Greetings from Kenya! Thank you for this useful tool we've been using bigbluebutton-exporter to get server and session stats. From the support group I've come across a comment indicating that the BBB-exporter tool causes a spike in CPU - I've not authenticated this yet.

But thank you so much for this piece of code.

**Comment by gitisara** [comment]
Thank you very much.

Please also add more functions such as Attendence managment within this.

Thanks again
